### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by DirtyF**

### CODE REVIEW

**Comment by DirtyF** [comment]
@oncletom I presume we don't care about maintaining old CI scripts ? 
I fixed the problem with the installation of graphicksmagick, but the script ask for a passphrase that causes the check to fail.

**Comment by oncletom** [comment]
I think it broke because of this https://blog.alwaysdata.com/2015/03/05/change-of-hostname-for-access-to-our-services/

Tried to address it via c8188f5.

**Comment by DirtyF** [comment]
@oncletom nice try, but the prompt still ask for a passphrase on Travis.

When I launch the same command from my machine, the server don't ask for a passphrase, maybe we need to update the authorized keys or something ?

**Comment by oncletom** [comment]
YAY!

screen shot 2016-02-19 at 14 33 11

**Pull request merged**
